[package]
name = "backend-system"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
rustls = "0.18"
actix-web = { version = "3", features = ["rustls"] }
actix-files = "0.3"